name: Fetch and Publish PoC-in-GitHub

on:
  schedule:
    - cron: '0 * * * *' # tiap jam
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python .github/scripts/fetch_pocs.py

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: add/pocs-${{ github.run_id }}
          title: "Auto Update PoCs - ${{ github.run_id }}"
          commit-message: "Auto Update PoCs"
          body: "This PR adds new PoCs fetched from poc-in-github."
